# Numpy introduction

Dimension:
if i have a matrix A $\in R^{3,3}$ the matrix has a mathematical dimension of $3\cdot3$ whilst the numpy dimension is 2 because it is a two dimension array. Ex a matrix B $\in R^{3, 4, 2}$ has a mathematical dimension of $3\cdot4\cdot2$ whilst the numpy dimension is 3 due to the three dimension

- object : the thing that i want to transform into an array
- neip : the dimension of the data to be memorized
- dtype : data type (unique to numpy ex np.float32(), np.float64(), np.int16())

### Array dim
- 0D array: scalar
- 1D array: vectors
- 2D array: matrix
- 3D array: 1D array of 2D array
arrays' dimension must be well defined due to the product between arrays 


In [18]:
import numpy as np

print("----------------------")
# two dimensional array
display(np.array([range(0,10,2)]))
# one dimensional array
display(np.array([item for item in range(0,10,2)]))

# matrix creation
# 5x1 zeros matrix
print(np.zeros(5))
# 5x4 zeros matrix
print(np.zeros((5, 4)))
# 2x3x2 ones tensor
print(np.ones((2, 3, 2)))

# prints the size of each dimension 
print(np.ones((3, 4, 5)).shape)

# To transpose a matrix
print(np.ones((2, 3)).T)

# To sum a given row or column
print(np.ones((2,3)).sum(axis=0))

----------------------


array([[0, 2, 4, 6, 8]])

array([0, 2, 4, 6, 8])

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
(3, 4, 5)
[[1. 1.]
 [1. 1.]
 [1. 1.]]


TypeError: _sum() got an unexpected keyword argument 'row'

in numpy all the operation are elements wise, instead of matrix wise (like matlab), to do a matrix multiplication use @